In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
from time import time
from datetime import datetime
from keras.callbacks import TensorBoard, ReduceLROnPlateau
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [96]:
df1 = pd.read_hdf('df_dataDOL1.hdf', key='hdf')
df2 = pd.read_hdf('df_dataDOL2.hdf', key='hdf')
df3 = pd.read_hdf('df_dataDOL3.hdf', key='hdf')

df_total = pd.concat([df1,df2,df3],  ignore_index=True)
df_total.head()

,Data,Contratos Abertos,Contratos Fechados,Número Negócios,Contratos Negociados,Volume,Abertura,Mínimo,Máximo,Médio,Último Preço,Ajuste,Var pontos,Última oferta de compra,Última oferta de venda
0,29/07/2019,851537,719017,27192,226625,42939771125,3.7850,3.7775,3.8015,3.789499,3.7820,3.784797,145520,3.7820,3.7825
1,26/07/2019,875047,851537,32128,309480,58414828000,3.7800,3.7610,3.7955,3.775030,3.7760,3.770245,125890,3.7765,3.7780
2,25/07/2019,890941,875047,41651,381060,72105906125,3.7680,3.7570,3.8070,3.784490,3.7795,3.782834,129780,3.7795,3.7805
3,24/07/2019,883412,890941,26137,269620,50725252625,3.7675,3.7540,3.7795,3.762721,3.7735,3.769856,31160,3.7735,3.7755
4,23/07/2019,880504,883412,33586,313840,59121712875,3.7450,3.7430,3.7820,3.767634,3.7750,3.772972,356000,3.7750,3.7770

In [97]:
df = df_total.copy()

df['Dif_contratos'] = df['Contratos Abertos'] -df['Contratos Fechados']
df['Dif_minmax'] = (df['Máximo'] - df['Mínimo'])*1000
df['Dif_abert_ultimo'] = (df['Último Preço'] - df['Abertura'])*1000
df['Dif_abert_ajuste'] = (df['Ajuste'] - df['Abertura'])*1000
df['Dif_abert_min'] = (df['Abertura'] - df['Mínimo'])*1000
df['Dif_abert_max'] = (df['Abertura'] - df['Máximo'])*1000
df['Dif_abert_medio'] = (df['Abertura'] - df['Médio'])*1000
df['Dif_ajuste_ultimo'] = (df['Ajuste'] - df['Último Preço'])*1000
df['Dif_ajuste_medio'] = (df['Ajuste'] - df['Médio'])*1000
df['Dif_ultimacomp_ultimavend'] = (df['Última oferta de venda'] - df['Última oferta de compra'])*1000

df['Contratos Negociados'] = df['Contratos Negociados']/10000
df['Número Negócios'] = df['Número Negócios']/100
df['Volume'] = df['Volume']/1000000000


def Ajuste_Normal(x):
    x = str(x)[:-3]
    x = x + '5'
    x = float(x)
    return x
    
    
df['Ajuste'] = df['Ajuste'].apply(Ajuste_Normal)

df = df.drop(columns = ['Contratos Abertos', 'Contratos Fechados'])


df_feature = df.set_index('Data') #Usado depois do treinamento


df.head()

,Data,Número Negócios,Contratos Negociados,Volume,Abertura,Mínimo,Máximo,Médio,Último Preço,Ajuste,...,Dif_contratos,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend
0,29/07/2019,271.92,22.6625,42.939771,3.7850,3.7775,3.8015,3.789499,3.7820,3.7845,...,132520,24.0,-3.0,-0.203,7.5,-16.5,-4.499,2.797,-4.702,0.5
1,26/07/2019,321.28,30.9480,58.414828,3.7800,3.7610,3.7955,3.775030,3.7760,3.7705,...,23510,34.5,-4.0,-9.755,19.0,-15.5,4.970,-5.755,-4.785,1.5
2,25/07/2019,416.51,38.1060,72.105906,3.7680,3.7570,3.8070,3.784490,3.7795,3.7825,...,15894,50.0,11.5,14.834,11.0,-39.0,-16.490,3.334,-1.656,1.0
3,24/07/2019,261.37,26.9620,50.725253,3.7675,3.7540,3.7795,3.762721,3.7735,3.7695,...,-7529,25.5,6.0,2.356,13.5,-12.0,4.779,-3.644,7.135,2.0
4,23/07/2019,335.86,31.3840,59.121713,3.7450,3.7430,3.7820,3.767634,3.7750,3.7725,...,-2908,39.0,30.0,27.972,2.0,-37.0,-22.634,-2.028,5.338,2.0

In [98]:
df_abert_old = df.copy()

#Regressão - Por isso foi retirado função que o maior que 0 vira 1


df_abert_old['target'] = df_abert_old.Ajuste.shift(-1) - df_abert_old['Ajuste']
#df_abert_old['target'] = df_abert_old['target'].apply(lambda x: 1 if x > 0 else 0)
#df_abert_old = df_abert_old.drop(df_abert_old.tail(1).index,inplace=True)

df_abert_old['Média'] = (df_abert_old['Último Preço'] + df_abert_old['Abertura'] + df_abert_old['Máximo'] + df_abert_old['Mínimo'] + df_abert_old['Médio'] + df_abert_old['Ajuste'] + df_abert_old['Última oferta de compra']+ df_abert_old['Última oferta de venda'])/8
df_abert_old = df_abert_old.drop(columns = ['Último Preço','Abertura','Máximo','Mínimo','Médio','Última oferta de compra','Última oferta de venda','Contratos Negociados', 'Ajuste'])


df_change = df_abert_old[['target']]
df_abert_old = df_abert_old.drop(columns = 'target')
df_abert_old['target'] = df_change

df_abert_old.head()

,Data,Número Negócios,Volume,Var pontos,Dif_contratos,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend,Média,target
0,29/07/2019,271.92,42.939771,145520,132520,24.0,-3.0,-0.203,7.5,-16.5,-4.499,2.797,-4.702,0.5,3.785562,-0.014
1,26/07/2019,321.28,58.414828,125890,23510,34.5,-4.0,-9.755,19.0,-15.5,4.970,-5.755,-4.785,1.5,3.776566,0.012
2,25/07/2019,416.51,72.105906,129780,15894,50.0,11.5,14.834,11.0,-39.0,-16.490,3.334,-1.656,1.0,3.779811,-0.013
3,24/07/2019,261.37,50.725253,31160,-7529,25.5,6.0,2.356,13.5,-12.0,4.779,-3.644,7.135,2.0,3.769465,0.003
4,23/07/2019,335.86,59.121713,356000,-2908,39.0,30.0,27.972,2.0,-37.0,-22.634,-2.028,5.338,2.0,3.767142,-0.035

In [99]:
sc = StandardScaler()
df_abert_old.iloc[:,1:-1]  = sc.fit_transform(df_abert_old.iloc[:,1:-1])



df_moeda = pd.read_csv('moedas_features.csv')

sc = StandardScaler()
df_moeda.iloc[:,1:] = sc.fit_transform(df_moeda.iloc[:,1:])

pca = PCA(n_components=3)
dataset = pca.fit_transform(df_moeda.iloc[:,1:])
df_moeda_pca = pd.DataFrame(dataset)
df_moeda_pca['Data'] = df_moeda.iloc[:,0:1]




df_abert = pd.merge(df_moeda_pca, df_abert_old, on = 'Data')



df_abert.head()

,0,1,2,Data,Número Negócios,Volume,Var pontos,Dif_contratos,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend,Média,target
0,1.498562,2.807394,0.723413,14/06/2019,2.866027,2.605075,1.099924,-0.181265,1.312951,1.557156,-0.120061,-0.332606,-2.054526,-1.942578,-0.196842,-0.178956,-0.012159,2.172473,-0.0390
1,2.236543,1.093142,0.813228,13/06/2019,2.062243,2.314778,-0.649583,-0.483705,-0.004695,-0.058399,-0.185437,0.076400,0.075670,0.280736,-0.182731,-0.177075,-0.011627,2.131167,-0.0030
2,1.688401,2.248905,0.239470,12/06/2019,2.508010,2.488214,-0.637310,-0.152949,0.440706,0.335639,-0.207215,0.785345,0.125209,0.694360,-0.223930,-0.186347,-0.012159,2.140346,-0.0030
3,2.172415,1.142010,0.374627,11/06/2019,1.687984,1.587085,0.608670,-0.243370,0.459265,-0.964686,-0.258551,1.303420,0.571064,1.353530,-0.211288,-0.217766,-0.011627,2.144963,0.0315
4,2.012423,1.412341,1.183179,10/06/2019,1.377429,1.242700,-0.457538,-0.009080,0.069538,-0.334226,-0.229939,0.676277,0.521525,0.804702,-0.213692,-0.205747,-0.010033,2.174529,-0.0105

In [100]:
df_abert['Data'] = df_abert['Data'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y'))
df_abert = df_abert.set_index('Data')
df_abert = df_abert.sort_index()
index = df_abert.index

In [101]:
y = df_abert[['target']]
X = df_abert.drop(columns = ['target'])
X_columns = df_abert.drop(columns = ['target'])

sc = StandardScaler()
X = sc.fit_transform(X)
#X = X.values
X

df_final = pd.DataFrame(X,index = index)

front = 1000

df_final = df_final.iloc[front:]
y = y.iloc[front:]

Teste para descobrir qual fatia dos dados tem melhor resultado com Random Forest

dict_res = {}

for i in range(0,4000,100):

y = df_abert[['target']]
X = df_abert.drop(columns = ['target'])
X_columns = df_abert.drop(columns = ['target'])

sc = StandardScaler()
X = sc.fit_transform(X)
#X = X.values
X

df_final = pd.DataFrame(X,index = index)

df_final = df_final.iloc[i:]
y = y.iloc[i:]

res_total = 0
soma = 0
for k in range(1,10):
    x_train, x_test, y_train, y_test = train_test_split(df_final, y, test_size=0.2, shuffle = False)

    r = RandomForestClassifier()
    r.fit(x_train, y_train)  

    predictions = r.predict(x_test)

    res = accuracy_score(y_test, predictions)
    res_total +=res
    soma+=1

dict_res[i] = res_total/soma

In [102]:
x_train, x_test, y_train, y_test = train_test_split(df_final, y, test_size=0.2, shuffle = False)

In [103]:
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(x_train, y_train)

predictions = regr.predict(x_test)

c:\users\choice\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\choice\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

---

In [104]:
index_target = y_test.index
df_target = pd.DataFrame(predictions, index = index_target)
df_target.columns = ['target']

In [105]:
df_inicial_target = pd.merge(df_feature,df_target, left_index = True, right_index = True)

In [106]:
df = df_inicial_target.copy()
df.head()

,Número Negócios,Contratos Negociados,Volume,Abertura,Mínimo,Máximo,Médio,Último Preço,Ajuste,Var pontos,...,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend,target
Data,,,,,,,,,,,,,,,,,,,,,
2016-10-26,364.72,36.8695,57.787096,3.1290,3.1185,3.1575,3.134683,3.1425,3.1495,378480,...,39.0,13.5,20.136,10.5,-28.5,-5.683,6.636,14.453,0.5,-0.008968
2016-10-27,374.85,34.8490,54.904726,3.1455,3.1305,3.1770,3.151007,3.1760,3.1515,28080,...,46.5,30.5,6.444,15.0,-31.5,-5.507,-24.056,0.937,1.5,-0.004692
2016-10-28,454.13,43.8080,69.825823,3.1665,3.1605,3.2080,3.187812,3.2060,3.2005,489720,...,47.5,39.5,34.416,6.0,-41.5,-21.312,-5.084,13.104,2.0,-0.019069
2016-10-31,15.61,1.4540,2.315106,3.1940,3.1765,3.1980,3.184465,3.1815,3.1500,198160,...,21.5,-12.5,-12.900,17.5,-4.0,9.535,-0.400,-3.365,0.5,0.002727
2016-11-01,196.36,18.6865,37.926872,4.0480,4.0270,4.0915,4.059280,4.0855,4.0715,100410,...,64.5,37.5,23.027,21.0,-43.5,-11.280,-14.473,11.747,2.5,-0.002319

In [107]:
df.loc[(df.target > 0), 'teste'] = df.Ajuste.shift(-1) - df.Abertura.shift(-1)
df.loc[(df.target < 0), 'teste'] = df.Abertura.shift(-1) - df.Ajuste.shift(-1)

df = df.dropna(0)

In [67]:
df.loc[(df.target > 0) & (df.Abertura.shift(-1) < df.Ajuste), 'teste'] = df.Ajuste.shift(-1) - df.Abertura.shift(-1)
df = df.dropna()

In [108]:
df['teste'].sum()

-19.339999999999996