In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
from time import time
from datetime import datetime
from keras.callbacks import TensorBoard, ReduceLROnPlateau

Using TensorFlow backend.

In [55]:
df1 = pd.read_hdf('df_dataDOL1.hdf', key='hdf')
df2 = pd.read_hdf('df_dataDOL2.hdf', key='hdf')
df3 = pd.read_hdf('df_dataDOL3.hdf', key='hdf')

df_total = pd.concat([df1,df2,df3],  ignore_index=True)
df_total.head()

,Data,Contratos Abertos,Contratos Fechados,Número Negócios,Contratos Negociados,Volume,Abertura,Mínimo,Máximo,Médio,Último Preço,Ajuste,Var pontos,Última oferta de compra,Última oferta de venda
0,29/07/2019,851537,719017,27192,226625,42939771125,3.7850,3.7775,3.8015,3.789499,3.7820,3.784797,145520,3.7820,3.7825
1,26/07/2019,875047,851537,32128,309480,58414828000,3.7800,3.7610,3.7955,3.775030,3.7760,3.770245,125890,3.7765,3.7780
2,25/07/2019,890941,875047,41651,381060,72105906125,3.7680,3.7570,3.8070,3.784490,3.7795,3.782834,129780,3.7795,3.7805
3,24/07/2019,883412,890941,26137,269620,50725252625,3.7675,3.7540,3.7795,3.762721,3.7735,3.769856,31160,3.7735,3.7755
4,23/07/2019,880504,883412,33586,313840,59121712875,3.7450,3.7430,3.7820,3.767634,3.7750,3.772972,356000,3.7750,3.7770

In [56]:
df = df_total.copy()

df['Dif_contratos'] = df['Contratos Abertos'] -df['Contratos Fechados']
df['Dif_minmax'] = (df['Máximo'] - df['Mínimo'])*1000
df['Dif_abert_ultimo'] = (df['Último Preço'] - df['Abertura'])*1000
df['Dif_abert_ajuste'] = (df['Ajuste'] - df['Abertura'])*1000
df['Dif_abert_min'] = (df['Abertura'] - df['Mínimo'])*1000
df['Dif_abert_max'] = (df['Abertura'] - df['Máximo'])*1000
df['Dif_abert_medio'] = (df['Abertura'] - df['Médio'])*1000
df['Dif_ajuste_ultimo'] = (df['Ajuste'] - df['Último Preço'])*1000
df['Dif_ajuste_medio'] = (df['Ajuste'] - df['Médio'])*1000
df['Dif_ultimacomp_ultimavend'] = (df['Última oferta de venda'] - df['Última oferta de compra'])*1000

df['Contratos Negociados'] = df['Contratos Negociados']/10000
df['Número Negócios'] = df['Número Negócios']/100
df['Volume'] = df['Volume']/1000000000


df = df.drop(columns = ['Contratos Abertos', 'Contratos Fechados'])


df_feature = df.set_index('Data') #Usado depois do treinamento


df.head()

,Data,Número Negócios,Contratos Negociados,Volume,Abertura,Mínimo,Máximo,Médio,Último Preço,Ajuste,...,Dif_contratos,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend
0,29/07/2019,271.92,22.6625,42.939771,3.7850,3.7775,3.8015,3.789499,3.7820,3.784797,...,132520,24.0,-3.0,-0.203,7.5,-16.5,-4.499,2.797,-4.702,0.5
1,26/07/2019,321.28,30.9480,58.414828,3.7800,3.7610,3.7955,3.775030,3.7760,3.770245,...,23510,34.5,-4.0,-9.755,19.0,-15.5,4.970,-5.755,-4.785,1.5
2,25/07/2019,416.51,38.1060,72.105906,3.7680,3.7570,3.8070,3.784490,3.7795,3.782834,...,15894,50.0,11.5,14.834,11.0,-39.0,-16.490,3.334,-1.656,1.0
3,24/07/2019,261.37,26.9620,50.725253,3.7675,3.7540,3.7795,3.762721,3.7735,3.769856,...,-7529,25.5,6.0,2.356,13.5,-12.0,4.779,-3.644,7.135,2.0
4,23/07/2019,335.86,31.3840,59.121713,3.7450,3.7430,3.7820,3.767634,3.7750,3.772972,...,-2908,39.0,30.0,27.972,2.0,-37.0,-22.634,-2.028,5.338,2.0

In [66]:
df_abert_old = df.copy()

#1 se o Ajuste for maior que a abertura

df_abert_old['target'] = df_abert_old.Ajuste.shift(-1) - df_abert_old.Abertura.shift(-1)
df_abert_old['target'] = df_abert_old['target'].apply(lambda x: 1 if x > 0 else 0)
df_abert_old = df_abert_old.drop(len(df_abert_old)-1)

df_abert_old['Média'] = (df_abert_old['Último Preço'] + df_abert_old['Abertura'] + df_abert_old['Máximo'] + df_abert_old['Mínimo'] + df_abert_old['Médio'] + df_abert_old['Ajuste'] + df_abert_old['Última oferta de compra']+ df_abert_old['Última oferta de venda'])/8
df_abert_old = df_abert_old.drop(columns = ['Último Preço','Abertura','Máximo','Mínimo','Médio','Última oferta de compra','Última oferta de venda','Contratos Negociados', 'Ajuste'])


df_change = df_abert_old[['target']]
df_abert_old = df_abert_old.drop(columns = 'target')
df_abert_old['target'] = df_change

df_abert_old.head()

,Data,Número Negócios,Volume,Var pontos,Dif_contratos,Dif_minmax,Dif_abert_ultimo,Dif_abert_ajuste,Dif_abert_min,Dif_abert_max,Dif_abert_medio,Dif_ajuste_ultimo,Dif_ajuste_medio,Dif_ultimacomp_ultimavend,Média,target
0,29/07/2019,271.92,42.939771,145520,132520,24.0,-3.0,-0.203,7.5,-16.5,-4.499,2.797,-4.702,0.5,3.785600,0
1,26/07/2019,321.28,58.414828,125890,23510,34.5,-4.0,-9.755,19.0,-15.5,4.970,-5.755,-4.785,1.5,3.776534,1
2,25/07/2019,416.51,72.105906,129780,15894,50.0,11.5,14.834,11.0,-39.0,-16.490,3.334,-1.656,1.0,3.779853,1
3,24/07/2019,261.37,50.725253,31160,-7529,25.5,6.0,2.356,13.5,-12.0,4.779,-3.644,7.135,2.0,3.769510,1
4,23/07/2019,335.86,59.121713,356000,-2908,39.0,30.0,27.972,2.0,-37.0,-22.634,-2.028,5.338,2.0,3.767201,0

In [67]:
sc = StandardScaler()

df_abert_old.iloc[:,1:-1]  = sc.fit_transform(df_abert_old.iloc[:,1:-1])

df_moeda = pd.read_csv('moedas_features.csv')

sc = StandardScaler()
df_moeda.iloc[:,1:] = sc.fit_transform(df_moeda.iloc[:,1:])

pca = PCA(n_components=3)
dataset = pca.fit_transform(df_moeda.iloc[:,1:])
df_moeda_pca = pd.DataFrame(dataset)
df_moeda_pca['Data'] = df_moeda.iloc[:,0:1]

df_abert = pd.merge(df_moeda_pca, df_abert_old, on = 'Data')

In [68]:
df_abert['Data'] = df_abert['Data'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y'))
df_abert = df_abert.set_index('Data')
df_abert = df_abert.sort_index()
index = df_abert.index

In [69]:
y = df_abert[['target']]
X = df_abert.drop(columns = ['target'])
X_columns = df_abert.drop(columns = ['target'])

sc = StandardScaler()
X = sc.fit_transform(X)
#X = X.values
X

array([[ 2.2662969 ,  1.88804075,  0.4199717 , ..., -0.20357272,
        -0.01448526, -0.55159947],
       [ 2.91088092,  0.57818227, -1.47667758, ..., -0.21720465,
        -0.01448526, -0.55704584],
       [ 2.64513826,  0.9399061 ,  0.91767333, ..., -0.22194049,
        -0.01448526, -0.5714771 ],
       ...,
       [ 0.82863615,  1.11620819,  0.13776343, ..., -0.20281729,
        -0.01402039,  1.97132267],
       [ 1.09805362,  0.54176438,  0.47191894, ..., -0.19421976,
        -0.01355552,  1.96200735],
       [ 0.73532849,  1.39379164,  0.41961084, ..., -0.19596445,
        -0.01402039,  2.00404183]])

In [70]:
df_final = pd.DataFrame(X,index = index)

In [71]:
x_train, x_test, y_train, y_test = train_test_split(df_final, y, test_size=0.2)

In [72]:
r = RandomForestClassifier()
r.fit(x_train, y_train)  

predictions = r.predict(x_test)

accuracy_score(y_test, predictions)

c:\users\choice\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\choice\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

0.5277108433734939